spring:
  application:
    name: simulador-analise-credito

  datasource:
    url: jdbc:postgresql://localhost:5432/simulador_analise_credito
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
